import { StyleSheet } from "react-native";
import { getMobileThemeVersion, theme } from "./theme";

function buildStyles() {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: theme.paper },
    screen: { flex: 1 },
    content: { padding: 18, paddingBottom: 108 },
    header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 18, gap: 12 },
    headerBack: { flexDirection: "row", alignItems: "center", gap: 10, minWidth: 0, flex: 1 },
    headerBackText: { color: theme.ink, fontSize: 18, fontWeight: "800", flexShrink: 1 },
    logo: { color: theme.ink, fontSize: 24, fontWeight: "800" },
    location: { color: theme.muted, marginTop: 4 },
    iconButton: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: theme.surface },
    search: { height: 48, borderRadius: 24, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", backgroundColor: theme.surface },
    searchText: { marginLeft: 8, color: theme.muted },
    searchInput: { flex: 1, minHeight: 48, marginLeft: 8, color: theme.ink, outlineStyle: "none" as never },
    filterRow: { gap: 8, paddingVertical: 16 },
    filterChipButton: { overflow: "hidden", borderRadius: 18, backgroundColor: theme.surface },
    filterChipButtonActive: { backgroundColor: theme.ink },
    filterChip: { paddingHorizontal: 13, paddingVertical: 9, color: theme.ink, fontWeight: "700" },
    filterChipActive: { color: theme.paper },
    timeCard: { minHeight: 168, overflow: "hidden", borderRadius: 28, paddingHorizontal: 18, paddingVertical: 16, justifyContent: "flex-end", marginTop: 14 },
    timeImage: { borderRadius: 28 },
    timeLabel: { color: theme.coloredText, fontWeight: "700", marginBottom: 4 },
    timeTitle: { color: theme.coloredText, fontSize: 26, lineHeight: 30, fontWeight: "800" },
    timeFilters: { color: theme.coloredMuted, marginTop: 6, lineHeight: 18 },
    storyRail: { flexGrow: 1, gap: 12, paddingVertical: 14, paddingHorizontal: 8, alignItems: "center", justifyContent: "center" },
    story: { width: 74, alignItems: "center" },
    storyRing: { width: 60, height: 60, borderRadius: 30, backgroundColor: theme.nar, alignItems: "center", justifyContent: "center", borderWidth: 3, borderColor: theme.surface },
    storyRingActive: { backgroundColor: theme.ink, borderColor: theme.nar },
    storyDiscount: { color: theme.coloredText, fontWeight: "800" },
    storyText: { color: theme.muted, marginTop: 7, fontSize: 12 },
    storyTextActive: { color: theme.nar, fontWeight: "800" },
    section: { marginTop: 10 },
    sectionTitle: { fontSize: 22, fontWeight: "800", color: theme.ink, marginBottom: 12 },
    sectionBody: { gap: 12 },
    wideItem: { flexDirection: "row", alignItems: "center", gap: 12 },
    wideImageBox: { width: 82, height: 82 },
    wideImage: { borderRadius: 20 },
    wideCopy: { flex: 1, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.line, paddingBottom: 12, minWidth: 0 },
    wideTitle: { color: theme.ink, fontWeight: "800", fontSize: 16 },
    wideMeta: { color: theme.muted, marginTop: 5 },
    miniGrid: { flexDirection: "row", gap: 12, marginTop: 22 },
    mini: { flex: 1, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.line, paddingTop: 14 },
    miniTitle: { color: theme.ink, fontWeight: "800", marginTop: 8 },
    miniSubtitle: { color: theme.muted, marginTop: 5, lineHeight: 18 },
    calendarBand: { flexDirection: "row", gap: 8, marginTop: 16, marginBottom: 8 },
    calendarChipButton: { flex: 1, overflow: "hidden", borderRadius: 18, backgroundColor: theme.surface },
    calendarChipButtonActive: { backgroundColor: theme.ink },
    calendarChip: { textAlign: "center", paddingVertical: 10, color: theme.ink, fontWeight: "700" },
    calendarChipActive: { color: theme.paper },
    offerItem: { flexDirection: "row", alignItems: "center", gap: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.line, paddingBottom: 14 },
    offerDiscount: { width: 74, height: 74, borderRadius: 37, textAlign: "center", textAlignVertical: "center", lineHeight: 74, color: theme.coloredText, backgroundColor: theme.nar, fontWeight: "900", fontSize: 16, overflow: "hidden" },
    profileSurface: { marginTop: 14, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.line, paddingTop: 18 },
    profilePoints: { color: theme.nar, fontSize: 78, fontWeight: "900", lineHeight: 82 },
    profileTitle: { color: theme.ink, fontSize: 26, fontWeight: "800" },
    profileText: { color: theme.muted, marginTop: 10, lineHeight: 21 },
    profileGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 18 },
    profileChip: { overflow: "hidden", borderRadius: 18, paddingHorizontal: 13, paddingVertical: 9, color: theme.ink, backgroundColor: theme.surface },
    detailPreview: { marginTop: 20, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.line, paddingTop: 14 },
    detailPreviewTitle: { color: theme.ink, fontSize: 18, fontWeight: "800", marginBottom: 8 },
    detailRow: { flexDirection: "row", justifyContent: "space-between", gap: 16, paddingVertical: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.line },
    detailLabel: { color: theme.muted, flex: 0.9 },
    detailValue: { color: theme.ink, fontWeight: "700", flex: 1.1, textAlign: "right" },
    detailHeroCard: { minHeight: 260, overflow: "hidden", borderRadius: 30, justifyContent: "flex-end", marginTop: 14 },
    detailHeroImage: { borderRadius: 30 },
    detailHeroOverlay: { padding: 20, backgroundColor: theme.overlay },
    detailHeroEyebrow: { color: theme.coloredText, fontWeight: "800", marginBottom: 8 },
    detailHeroTitle: { color: theme.coloredText, fontSize: 28, lineHeight: 32, fontWeight: "900" },
    detailHeroSubtitle: { color: theme.coloredMuted, marginTop: 8, lineHeight: 20 },
    statStrip: { flexDirection: "row", gap: 8, marginTop: 14 },
    statItem: { flex: 1, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.line, paddingTop: 12 },
    statLabel: { color: theme.muted, fontSize: 12 },
    statValue: { color: theme.ink, fontSize: 16, fontWeight: "900", marginTop: 4 },
    subsectionGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12 },
    subsectionChip: { overflow: "hidden", borderRadius: 18, paddingHorizontal: 12, paddingVertical: 8, color: theme.ink, backgroundColor: theme.surface, fontWeight: "700" },
    actionRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 14 },
    actionPill: { flexGrow: 1, flexBasis: 0, minHeight: 38, borderRadius: 19, paddingHorizontal: 13, alignItems: "center", justifyContent: "center", backgroundColor: theme.ink },
    actionPillSecondary: { backgroundColor: theme.surface, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.line },
    actionPillText: { color: theme.paper, fontWeight: "800" },
    actionPillTextSecondary: { color: theme.ink, fontWeight: "800" },
    emptyText: { color: theme.muted, lineHeight: 21, paddingVertical: 10 },
    detailLinkRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.line, paddingVertical: 12 },
    detailLinkLabelWrap: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1, minWidth: 0 },
    detailLinkLabel: { color: theme.ink, fontWeight: "800" },
    detailLinkValue: { color: theme.muted, flex: 1.2, textAlign: "right" },
    settingsCard: { marginTop: 14, padding: 14, borderRadius: 22, backgroundColor: theme.surface, gap: 10 },
    settingsTitle: { color: theme.ink, fontSize: 18, fontWeight: "800" },
    settingsRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, paddingVertical: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.line },
    settingsLabel: { flex: 1, color: theme.ink, fontWeight: "700" },
    settingsValue: { color: theme.muted, textAlign: "right" },
    tabBar: { position: "absolute", left: 12, right: 12, bottom: 10, height: 72, borderRadius: 28, backgroundColor: theme.surface, flexDirection: "row", alignItems: "center", justifyContent: "space-around", shadowColor: theme.shadow, shadowOpacity: 0.12, shadowRadius: 28, shadowOffset: { width: 0, height: 12 } },
    tab: { alignItems: "center", gap: 4, minWidth: 54 },
    tabText: { color: theme.muted, fontSize: 11 },
    tabActive: { color: theme.nar, fontWeight: "800" },
    startupScreen: { flex: 1, backgroundColor: theme.paper },
    startupScroll: { flex: 1 },
    startupContent: { padding: 20, paddingTop: 14, paddingBottom: 28, gap: 14, minHeight: "100%" },
    splashCard: { minHeight: 210, borderRadius: 32, backgroundColor: theme.surface, padding: 22, justifyContent: "space-between", overflow: "hidden", borderWidth: StyleSheet.hairlineWidth, borderColor: theme.line },
    splashBrandRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 14 },
    splashLogo: { color: theme.ink, fontSize: 28, fontWeight: "900" },
    splashBadge: { color: theme.nar, fontWeight: "800" },
    splashTagline: { color: theme.muted, lineHeight: 22, maxWidth: 320 },
    splashAccent: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    splashPill: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 16, backgroundColor: theme.paper, color: theme.ink, fontWeight: "700" },
    onboardingCard: { borderRadius: 28, backgroundColor: theme.surface, padding: 18, gap: 14, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.line },
    onboardingTitle: { color: theme.ink, fontSize: 24, fontWeight: "900" },
    onboardingText: { color: theme.muted, lineHeight: 21 },
    onboardingSectionTitle: { color: theme.ink, fontSize: 16, fontWeight: "800", marginBottom: 10 },
    onboardingChoiceRow: { flexDirection: "row", flexWrap: "wrap", justifyContent: "center", gap: 10 },
    onboardingChoice: { minWidth: 88, borderRadius: 18, paddingHorizontal: 14, paddingVertical: 10, backgroundColor: theme.paper, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.line, alignItems: "center" },
    onboardingChoiceActive: { backgroundColor: theme.ink, borderColor: theme.ink, color: theme.paper },
    onboardingChoiceText: { color: theme.ink, fontWeight: "700" },
    onboardingChoiceTextActive: { color: theme.paper, fontWeight: "700" },
    onboardingAction: { borderRadius: 22, minHeight: 50, alignItems: "center", justifyContent: "center", backgroundColor: theme.nar, marginTop: 8, marginHorizontal: 8 },
    onboardingActionSecondary: { backgroundColor: theme.surface, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.line },
    onboardingActionText: { color: theme.paper, fontWeight: "800" },
    onboardingActionTextSecondary: { color: theme.ink, fontWeight: "800" },
    onboardingList: { gap: 10, paddingTop: 4 },
    onboardingListItem: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
    onboardingListText: { color: theme.muted, lineHeight: 20, flex: 1 },
    authInput: { minHeight: 50, borderRadius: 18, borderWidth: StyleSheet.hairlineWidth, borderColor: theme.line, backgroundColor: theme.paper, paddingHorizontal: 14, color: theme.ink }
  });
}

const cache = new Map<number, ReturnType<typeof buildStyles>>();

function getStyles() {
  const version = getMobileThemeVersion();
  const cached = cache.get(version);
  if (cached) return cached;
  const next = buildStyles();
  cache.set(version, next);
  return next;
}

export const styles = new Proxy({} as ReturnType<typeof buildStyles>, {
  get(_target, property: string | symbol) {
    const sheet = getStyles();
    return (sheet as Record<string, unknown>)[property as string];
  }
});
